# Generated by Django 5.0.2 on 2024-03-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
