# Generated by Django 5.0.2 on 2024-03-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_bookmark_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
