# Generated by Django 5.0.2 on 2024-03-23 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_bookmark_summary_alter_bookmark_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='note',
            new_name='notes',
        ),
    ]
