# Generated by Django 5.0.2 on 2024-03-26 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_rename_note_bookmark_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
